CASE_STATES = frozenset(
    {
        "DRAFT", "DOCUMENTS_READY", "QUESTIONS_GENERATING",
        "QUESTIONS_GENERATED", "QUESTIONS_APPROVED", "READY_FOR_ASSESSMENT",
        "ASSESSMENT_IN_PROGRESS", "ASSESSMENT_SUBMITTED", "AI_ANALYZING",
        "INTERVIEW_BRIEF_READY", "LIVE_INTERVIEW_IN_PROGRESS",
        "LIVE_INTERVIEW_COMPLETED", "EVALUATION_PENDING", "EVALUATED",
        "DOCUMENT_PARSE_FAILED", "QUESTION_GENERATION_FAILED",
        "ASSESSMENT_INTERRUPTED", "ASSESSMENT_EXPIRED", "AI_ANALYSIS_FAILED",
        "CANDIDATE_NO_SHOW", "CANCELLED",
    }
)

REFINED_CASE_STATES = frozenset(
    {
        "DRAFT", "DOCUMENTS_READY", "QUESTIONS_GENERATING",
        "QUESTIONS_GENERATED", "QUESTIONS_EXPORTED", "ANSWERS_IMPORTED",
        "AI_ANALYZING", "AI_EVALUATED", "QUESTION_GENERATION_FAILED",
        "AI_ANALYSIS_FAILED",
    }
)

ATTEMPT_TERMINAL_STATES = frozenset({"ASSESSMENT_SUBMITTED", "ASSESSMENT_EXPIRED"})
AI_TASK_TERMINAL_STATES = frozenset({"COMPLETED", "FAILED"})
